# -*- coding: utf-8 -*-
"""phase 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wb2mGghKcc8TskwQLlSy9jS5G2RZIleR
"""

from google.colab import files
uploaded = files.upload()
import pandas as pd
import seaborn as sns
import numpy as np

# Load the CSV file
df = pd.read_csv('market_trend_data.csv')

# Display the first few rows
df.head()

# Data info
print("\nData Info:")
print(df.info())



# Check for missing values
print(df.isnull().sum())

# Summary statistics
print(df.describe(include='all'))

# Fill missing values (optional)
df_filled = df.fillna(method='ffill')  # forward fill

# Plot market trend counts
import matplotlib.pyplot as plt
df['Market Trend'].value_counts().plot(kind='bar', title='Market Trend Distribution')
plt.show()

#  Correlation matrix
numeric_df = df.select_dtypes(include=[np.number])
correlation = numeric_df.corr()
plt.figure(figsize=(8, 6))
sns.heatmap(correlation, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

#  Group by Market Trend and calculate mean
grouped = df.groupby('Market Trend').mean(numeric_only=True)
print("\nGrouped by Market Trend (mean values):")
print(grouped)

#  Fill missing values (forward fill as an example)
df_ffill = df.fillna(method='ffill')

#  Visualize filled data
plt.figure(figsize=(6,4))
df_ffill['Revenue ($M)'].plot(kind='line', marker='o', title='Revenue Over Time')
plt.xticks(rotation=45)
plt.ylabel('Revenue ($M)')
plt.tight_layout()
plt.show()